"""add cv fields to profiles

Revision ID: a777efbd35e8
Revises: 2e8247f6b3e7
Create Date: 2026-07-14 04:11:41.865091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a777efbd35e8'
down_revision = '2e8247f6b3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cv_stored_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cv_content_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cv_file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cv_uploaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('cv_uploaded_at')
        batch_op.drop_column('cv_file_size')
        batch_op.drop_column('cv_content_type')
        batch_op.drop_column('cv_stored_filename')
        batch_op.drop_column('cv_original_filename')

    # ### end Alembic commands ###
